services:
  react-app:
    build: .
    ports:
      - "5173:5173"  # Viteのデフォルトポート
    volumes:
      - ./app:/app    # ホストとコンテナ間でファイル同期
      - /app/node_modules  # コンテナ内のnode_modulesを保持
    working_dir: /app    # コンテナ内で作業するディレクトリ
    command: sh -c "npm install && npm run dev"  # 初回インストールと起動
